version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    ports:
      - "8080:8080" # 로컬에서 8080 포트로 접속
    environment:
      SPRING_PROFILES_ACTIVE: prod # 프로파일 설정
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: my-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: beautymeongdang
      MYSQL_USER: testuser
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
