name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master # PR 생성 시 테스트 실행
  push:
    branches:
      - master # main 브랜치에 Push 발생 시 배포 진행

jobs:
  # 1. PR에서의 테스트 및 코드 검증
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean test -Dspring.profiles.active=test

  # 2. Push 이벤트 시 빌드 및 배포
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' # Push 이벤트 시에만 실행
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2 # 원하는 AWS 리전 지정

      - name: Build JAR file
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -Dspring.profiles.active=test

      - name: Copy JAR to build context
        run: cp build/libs/beauty-meongdang-service-*-SNAPSHOT.jar .

      - name: Build Docker image
        run: |
          docker build -t beauty-meongdang:latest .
          docker tag beauty-meongdang:latest ${{ secrets.DOCKER_USERNAME }}/beauty-meongdang:latest

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/beauty-meongdang:latest

      - name: Create application.properties
        run: |
          mkdir -p src/main/resources
          echo "spring.datasource.url=jdbc:h2:mem:testdb" >> src/main/resources/application.properties
          echo "spring.datasource.driver-class-name=org.h2.Driver" >> src/main/resources/application.properties
          echo "spring.datasource.username=sa" >> src/main/resources/application.properties
          echo "spring.datasource.password=password" >> src/main/resources/application.properties
          echo "spring.jpa.hibernate.ddl-auto=create-drop" >> src/main/resources/application.properties

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.EC2_SERVER_IP }}
          SERVER_USER: ${{ secrets.EC2_SERVER_USER }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && \
            cd /home/ubuntu/app && \
            docker-compose pull && \
            docker-compose up -d
          "
